E2E Tests for booking functionality
joel-gouveia/frs-booking pull request #65
Opened 2024-02-02 15:55 UTC by mathvaillant

# Most of the changes are test cases.

- [ ] Screen flow
- [ ] Keyboard flow

2024-02-02 16:02 UTC, mathvaillant commented
![](https://github.trello.services/images/mini-trello-icon.png) [End to end test for Ticket Type Group (Booking tickets)](https://trello.com/c/wAunIH8g/55-end-to-end-test-for-ticket-type-group-booking-tickets)

2024-02-14 09:45 UTC, joel-gouveia commented on .github/workflows/e2e-tests.yaml
> +name: Run E2E tests
Is this still taking 30 minutes to complete? I don't want to block PRs for that long. I know they take longer to review but I would prefer to run this locally before each release

2024-02-14 09:46 UTC, joel-gouveia requested changes
Take a look at my comment please

2024-02-15 08:39 UTC, joaoqueiroz95 approved these changes
Good job

2024-02-15 08:49 UTC, joaoqueiroz95 commented on e2e/features/bookingTickets/ScreenFlow.test.ts
> +    const passengers = element(by.text(PASSENGERS_GROUP.name).withAncestor(ticketGroupsList));
You could include the commonActionsBeforeBooking inside the beforeEach, since every test calls it

2024-02-15 08:50 UTC, joaoqueiroz95 commented on e2e/features/bookingTickets/ScreenFlow.test.ts
> +  it(`
Super minor, but I would include a new line between the tests

2024-02-15 08:52 UTC, joaoqueiroz95 commented on e2e/features/bookingTickets/ScreenFlow.test.ts
> +    await vehicles.tap();
Also very minor, but everything is too condensed together, no new lines. For example, here I would include a newline after the expect in line 297

2024-02-21 11:34 UTC, joel-gouveia requested changes
Lets disabled the .yaml file. Everything else looks good

2024-02-21 13:00 UTC, mathvaillant commented
> Lets disabled the .yaml file. Everything else looks good

Done.

2024-02-22 11:02 UTC, joel-gouveia approved these changes

2024-02-22 11:31 UTC, merged