Feat/boarding rework
joel-gouveia/frs-booking pull request #69
Opened 2024-02-09 09:49 UTC by joaoqueiroz95

[Uploading new-deboard.webm…]()

2024-02-15 11:29 UTC, joel-gouveia commented on src/screens/Boarding.tsx
> +          title: "Boarding",
i8

2024-02-15 11:29 UTC, joel-gouveia commented on src/screens/Boarding.tsx
> +            subtitle: "Main Menu",
i8

2024-02-15 11:29 UTC, joel-gouveia requested changes
Small changes but looks good

2024-02-16 10:42 UTC, mathvaillant approved these changes

2024-02-16 10:43 UTC, joel-gouveia approved these changes
LGTM!

2024-02-16 10:43 UTC, merged