Feat/skip one route
joel-gouveia/frs-booking pull request #75
Opened 2024-02-19 12:05 UTC by joaoqueiroz95

-When there is only 1 route, skip to Main Menu
-Do not show "Choose Route" in drawer, when there is only 1 route
-Improved Summary component UI
-Added key pressing for Cancellation screen

2024-02-19 12:07 UTC, joaoqueiroz95 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Route - Skip screen if only 1 route](https://trello.com/c/QTSQW9os/77-route-skip-screen-if-only-1-route)

2024-02-21 10:47 UTC, mathvaillant approved these changes

2024-02-23 10:25 UTC, joel-gouveia commented on src/screens/RouteSelection/RouteSelection.tsx
> +        }
what if no `res` for some reason?

2024-02-23 10:25 UTC, joel-gouveia commented on src/screens/RouteSelection/RouteSelection.tsx
> +        }
This would throw an error and crash

2024-02-23 10:33 UTC, joel-gouveia requested changes
Make sure to catch errors with api calls

2024-02-23 10:38 UTC, mathvaillant commented
> Make sure to catch errors with api calls

Isn't it a ticket itself? Specifically the #27 on Trello

2024-02-23 11:01 UTC, joaoqueiroz95 commented on src/screens/RouteSelection/RouteSelection.tsx
> +        }
I think there are many places where this could happen, not only this API response.
I think we should deal with that on a separate ticket.

2024-02-27 10:18 UTC, merged