Feat/inform when summary empty
joel-gouveia/frs-booking pull request #87
Opened 2024-02-23 06:24 UTC by joaoqueiroz95

[Uploading disable-btn.webm…]()

2024-02-23 06:26 UTC, joaoqueiroz95 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Booking Summary - Disable button if no tickets selected](https://trello.com/c/BPOK2JNM/82-booking-summary-disable-button-if-no-tickets-selected)

2024-02-23 10:31 UTC, joel-gouveia commented on src/screens/__tests__/TicketSelection.test.tsx
> +  it("should not navigate to summary, when clicking on Summary button and no tickets is elected", async () => {
why are tickets elected in this application? who are the voters?

2024-02-23 10:31 UTC, joel-gouveia requested changes
Minor text change, it can be merged afterwards

2024-02-23 10:45 UTC, joaoqueiroz95 commented on src/screens/__tests__/TicketSelection.test.tsx
> +  it("should not navigate to summary, when clicking on Summary button and no tickets is elected", async () => {
I meant selected

2024-02-23 10:53 UTC, mathvaillant approved these changes

2024-02-27 11:21 UTC, joel-gouveia approved these changes

2024-02-27 11:25 UTC, mathvaillant commented
LGTM!

2024-02-27 11:33 UTC, mathvaillant commented
Tests fail. Missing mock of `useKeyboardEvents` at your `Cancellation.test.tsx`.

```
jest.mock("@hooks/useKeyboardEvents", () => {
  return {
    useKeyboardEvents: jest.fn(),
  };
});
```

2024-02-27 16:49 UTC, merged